### ISSUE TITLE
Urls tab fails to parse links

### ISSUE THREAD

**Issue by Zi0MIX** [schneidermanuel/TwitchLeecher-Dx#12]
**Description**
Link parsed to the text box in Urls is not parsed. After pressing search nothing happens, but when i come back to Channel tab it complains about an empty field, seems like it's trying to read the input from there. 
However if i switch to Urls tab from IDs tab, it behaves normally, the link is parsed as it should.

**Steps to reproduce**
Open the program, go directly to Urls section, paste a link and press Search

**Information**
- Windows 10 PRO 64bit 22H2
- Tried on this URL: https://www.twitch.tv/videos/2077850274

**Additional information that might be useful**
It correlates with the Urls tab button being or not being highlighted, it highlights visually when switching from IDs tab and also that's when the Urls are being parsed

Used executable from this release https://github.com/schneidermanuel/TwitchLeecher-Dx/releases/tag/v3.4.0

**Comment by franklinalvarezn** [comment]
When trying to download any live video or clip, it shows me this error or warning.

_**Steps to reproduce**_

Open the program, go to any of the options that allow you to download either with added channel names or twitch links.

_**Information**_

LINUX Deepin 23 

_**Error**_

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 83

Starting parallel video chunk download
Number of video chunks to download: 83
Maximum connection count: 2

Parallel video chunk download is running...

Starting temporary download folder cleanup!
Deleting directory '/home/Alvarez/.local/share/Temp/7dd820b9b12b4beba91f35d36bb90545'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. (One or more errors occurred. (Response status code does not indicate success: 403 (Forbidden).))
 ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 403 (Forbidden).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage , CancellationToken )
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState) in /home/manuel/git/TwitchLeecher-DX/src/TwitchLeecher-Dx-3.4.0-beta3/TwitchLeecher/TwitchLeecher.Services/Services/DownloadService.cs:line 528
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& , Int32 , Boolean& )
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& , Int32 , Boolean& )
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& )
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 , ParallelOptions , Boolean )
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 , Int32 , ParallelOptions , Action`1 , Action`2 , Func`4 , Func`1 , Action`1 )
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection , CancellationToken , Exception )
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 , Int32 , ParallelOptions , Action`1 , Action`2 , Func`4 , Func`1 , Action`1 )
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 , ParallelOptions , Action`1 , Action`2 , Action`3 , Func`4 , Func`5 , Func`1 , Action`1 )
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 , ParallelOptions , Action`1 , Action`2 , Action`3 , Func`4 , Func`5 , Func`1 , Action`1 )
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 , ParallelOptions , Action`2 )
   at TwitchLeecher.Services.Services.DownloadService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, TwitchPlaylist vodPlaylist, CancellationToken cancellationToken) in /home/manuel/git/TwitchLeecher-DX/src/TwitchLeecher-Dx-3.4.0-beta3/TwitchLeecher/TwitchLeecher.Services/Services/DownloadService.cs:line 514
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2() in /home/manuel/git/TwitchLeecher-DX/src/TwitchLeecher-Dx-3.4.0-beta3/TwitchLeecher/TwitchLeecher.Services/Services/DownloadService.cs:line 227
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object )
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& , Thread )
   --- End of inner exception stack trace ---
