### ISSUE TITLE
I downloaded a video for over 2 hours and encountered this error halfway through. Could you please help me

### ISSUE THREAD

**Issue by zhuchenghao1337** [schneidermanuel/TwitchLeecher-Dx#26]
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 3.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 2138195692
Selected Quality: Source (1920x1080)
Download Url: https://www.twitch.tv/videos/2138195692
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: D:\twitch视频下载\beaulo\20240506_Beaulo_2138195692.mp4
FFMPEG Path: D:\software\TwitchLeecher-Dx\ffmpeg.exe
Temporary Download Folder: C:\Users\hankyou2\AppData\Local\Temp\2feb0956c93a4a4dbc268d4e562a47b1

Retrieving VOD access information... done!

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1715038067%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A2138195692%7D
Signature: a17262046bb87d05e0b9ad1f4b96c177d7ae76ca
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\hankyou2\AppData\Local\Temp\2feb0956c93a4a4dbc268d4e562a47b1'... done!

Retrieving playlist information for all VOD qualities... done!

PLAYLIST INFO
--------------------------------------------------------------------------------------------
Playlist for quality 'Source' is 'https://d2nvs31859zcd8.cloudfront.net/7a5dc8b84842f154e686_beaulo_44148054491_1714933961/chunked/index-dvr.m3u8'
Playlist for quality '720p60' is 'https://d2nvs31859zcd8.cloudfront.net/7a5dc8b84842f154e686_beaulo_44148054491_1714933961/720p60/index-dvr.m3u8'
Playlist for quality '480p30' is 'https://d2nvs31859zcd8.cloudfront.net/7a5dc8b84842f154e686_beaulo_44148054491_1714933961/480p30/index-dvr.m3u8'
Playlist for quality 'Audio Only' is 'https://d2nvs31859zcd8.cloudfront.net/7a5dc8b84842f154e686_beaulo_44148054491_1714933961/audio_only/index-dvr.m3u8'
Playlist for quality '360p30' is 'https://d2nvs31859zcd8.cloudfront.net/7a5dc8b84842f154e686_beaulo_44148054491_1714933961/360p30/index-dvr.m3u8'
Playlist for quality '160p30' is 'https://d2nvs31859zcd8.cloudfront.net/7a5dc8b84842f154e686_beaulo_44148054491_1714933961/160p30/index-dvr.m3u8'

Playlist url for selected quality 'Source (1920x1080)' is 'https://d2nvs31859zcd8.cloudfront.net/7a5dc8b84842f154e686_beaulo_44148054491_1714933961/chunked/index-dvr.m3u8'

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 945

Starting parallel video chunk download
Number of video chunks to download: 945
Maximum connection count: 10

Parallel video chunk download is running...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\hankyou2\AppData\Local\Temp\2feb0956c93a4a4dbc268d4e562a47b1'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. (One or more errors occurred. (Error while copying content to a stream.))
 ---> System.AggregateException: One or more errors occurred. (Error while copying content to a stream.)
 ---> System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState) in E:\Coding\twitchleecher-dx\TwitchLeecher\TwitchLeecher.Services\Services\DownloadService.cs:line 528
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.DownloadService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, TwitchPlaylist vodPlaylist, CancellationToken cancellationToken) in E:\Coding\twitchleecher-dx\TwitchLeecher\TwitchLeecher.Services\Services\DownloadService.cs:line 514
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2() in E:\Coding\twitchleecher-dx\TwitchLeecher\TwitchLeecher.Services\Services\DownloadService.cs:line 227
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---

**Comment by positron7120** [comment]
I am also facing the same issue with every stream I try to download. It downloads the majority of the video chunks and then spits out this error.
```
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 3.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 2122419933
Selected Quality: 1080p60 (1920x1080)
Download Url: https://www.twitch.tv/videos/2122419933
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: D:\Other Stuff\E&K streams\20240418_005646_2122419933_Husband & Wife play new SUPERNATURAL crafting_survival game (Once Human) #ad.mp4
FFMPEG Path: C:\Program Files (x86)\TwitchLeecher-Dx\ffmpeg.exe
Temporary Download Folder: D:\Other Stuff\E&K streams\Temp\ccdc5e4c5c794253928c6772f6278e59

Retrieving VOD access information... done!

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1715052910%2C%22https_required%22%3Atrue%2C%22privileged%22%3Atrue%2C%22user_id%22%3A122749776%2C%22version%22%3A2%2C%22vod_id%22%3A2122419933%7D
Signature: 1a538a8165c57025c2637bc21a9605dd218e4c13
Sub-Only: Yes
Privileged: Yes

Creating temporary download directory 'D:\Other Stuff\E&K streams\Temp\ccdc5e4c5c794253928c6772f6278e59'... done!

Retrieving playlist information for all VOD qualities... done!

PLAYLIST INFO
--------------------------------------------------------------------------------------------
Playlist for quality '1080p60' is 'https://d2nvs31859zcd8.cloudfront.net/9c15ace952d2c996b28e_evanandkatelyn_44040907387_1713382001/chunked/index-dvr.m3u8'
Playlist for quality '720p60' is 'https://d2nvs31859zcd8.cloudfront.net/9c15ace952d2c996b28e_evanandkatelyn_44040907387_1713382001/720p60/index-dvr.m3u8'
Playlist for quality '720p' is 'https://d2nvs31859zcd8.cloudfront.net/9c15ace952d2c996b28e_evanandkatelyn_44040907387_1713382001/720p30/index-dvr.m3u8'
Playlist for quality '480p' is 'https://d2nvs31859zcd8.cloudfront.net/9c15ace952d2c996b28e_evanandkatelyn_44040907387_1713382001/480p30/index-dvr.m3u8'
Playlist for quality 'Audio Only' is 'https://d2nvs31859zcd8.cloudfront.net/9c15ace952d2c996b28e_evanandkatelyn_44040907387_1713382001/audio_only/index-dvr.m3u8'
Playlist for quality '360p' is 'https://d2nvs31859zcd8.cloudfront.net/9c15ace952d2c996b28e_evanandkatelyn_44040907387_1713382001/360p30/index-dvr.m3u8'
Playlist for quality '160p' is 'https://d2nvs31859zcd8.cloudfront.net/9c15ace952d2c996b28e_evanandkatelyn_44040907387_1713382001/160p30/index-dvr.m3u8'

Playlist url for selected quality '1080p60 (1920x1080)' is 'https://d2nvs31859zcd8.cloudfront.net/9c15ace952d2c996b28e_evanandkatelyn_44040907387_1713382001/chunked/index-dvr.m3u8'

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 2022

Starting parallel video chunk download
Number of video chunks to download: 2022
Maximum connection count: 10

Parallel video chunk download is running...

Starting temporary download folder cleanup!
Deleting directory 'D:\Other Stuff\E&K streams\Temp\ccdc5e4c5c794253928c6772f6278e59'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. (One or more errors occurred. (The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.))
 ---> System.AggregateException: One or more errors occurred. (The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.)
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState) in E:\Coding\twitchleecher-dx\TwitchLeecher\TwitchLeecher.Services\Services\DownloadService.cs:line 528
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.DownloadService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, TwitchPlaylist vodPlaylist, CancellationToken cancellationToken) in E:\Coding\twitchleecher-dx\TwitchLeecher\TwitchLeecher.Services\Services\DownloadService.cs:line 514
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2() in E:\Coding\twitchleecher-dx\TwitchLeecher\TwitchLeecher.Services\Services\DownloadService.cs:line 227
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
```

**Comment by zhuchenghao1337** [comment]
I ultimately gave up on this project and chose other options.The principle is to download from M3UB. You should be able to find other alternative solutions by exploring this. come on

**Comment by positron7120** [comment]
@zhuchenghao1337 could you check whether version 3.6.0 has fixed this error for you? As, it is fixed for me.

**Comment by schneidermanuel** [comment]
Is this error still present in the current version 3.6?
