### ISSUE TITLE
The download runs and stops after a while

### ISSUE THREAD

**Issue by d-plusk** [schneidermanuel/TwitchLeecher-Dx#43]
**Description**
Describe, what the issue is

**Steps to reproduce**
I drop in a VOD URL
It appears in the search list
I click the download icon
Then press Download and it says "downloaded added"
It is downloading and suddenly 100% is displayed and the status shows an error

**Information**
- Twitch VOD URL: https://www.twitch.tv/videos/2230398333
- Twitch Leecher-DX log file:  I don't see a log file being generated
- Download logs: [Twitch Leecher-DX log file.txt](https://github.com/user-attachments/files/16732222/Twitch.Leecher-DX.log.file.txt)
- Operating System: Windows 11

**Additional information that might be useful**
I'm using current version 3.7
It had charged up to 30% and then cancelled with an error message, which can be seen in the picture.
Screen: ![image](https://github.com/user-attachments/assets/efacceee-937a-418a-938d-c3cc84f66756)

**Comment by schneidermanuel** [comment]
After the download crashed, you can get to the log using the rightmost of the 3 Buttons on the download. 
One for Retry, one for delete, and one for log.
I am happy to investigate this issue, but I need to see the log file

**Comment by d-plusk** [comment]
Thank you for your quick reply.
Unfortunately, I am travelling for three weeks and will not be able to send you the protocols. I will make the protocols available to you after the three weeks have passed.

**Comment by positron7120** [comment]
It seems when there is some slight Internet slow-downs the download just goes into error without retrying this is the error I have received.
```Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 3.7

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 2298615869
Selected Quality: 1080p60 (1920x1080)
Download Url: https://www.twitch.tv/videos/2298615869
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: D:\Other Stuff\E&K streams\20241111_010127_2298615869_Saving the planet (Planet Crafter).mp4
FFMPEG Path: C:\Program Files (x86)\TwitchLeecher-Dx\ffmpeg.exe
Temporary Download Folder: D:\Other Stuff\E&K streams\Temp\7692587d6d15480f8909fbe29291c338

Retrieving VOD access information... done!

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1731547293%2C%22https_required%22%3Atrue%2C%22privileged%22%3Atrue%2C%22user_id%22%3A122749776%2C%22version%22%3A2%2C%22vod_id%22%3A2298615869%7D
Signature: 661da643edb15493b52c0e0afc51b3ac8d18573d
Sub-Only: Yes
Privileged: Yes

Creating temporary download directory 'D:\Other Stuff\E&K streams\Temp\7692587d6d15480f8909fbe29291c338'... done!

Retrieving playlist information for all VOD qualities... done!

PLAYLIST INFO
--------------------------------------------------------------------------------------------
Playlist for quality '1080p60' is 'https://d2nvs31859zcd8.cloudfront.net/54b18845c641d1343e6f_evanandkatelyn_39467301940_1731267082/chunked/index-dvr.m3u8'
Playlist for quality '720p60' is 'https://d2nvs31859zcd8.cloudfront.net/54b18845c641d1343e6f_evanandkatelyn_39467301940_1731267082/720p60/index-dvr.m3u8'
Playlist for quality '720p' is 'https://d2nvs31859zcd8.cloudfront.net/54b18845c641d1343e6f_evanandkatelyn_39467301940_1731267082/720p30/index-dvr.m3u8'
Playlist for quality '480p' is 'https://d2nvs31859zcd8.cloudfront.net/54b18845c641d1343e6f_evanandkatelyn_39467301940_1731267082/480p30/index-dvr.m3u8'
Playlist for quality 'Audio Only' is 'https://d2nvs31859zcd8.cloudfront.net/54b18845c641d1343e6f_evanandkatelyn_39467301940_1731267082/audio_only/index-dvr.m3u8'
Playlist for quality '360p' is 'https://d2nvs31859zcd8.cloudfront.net/54b18845c641d1343e6f_evanandkatelyn_39467301940_1731267082/360p30/index-dvr.m3u8'
Playlist for quality '160p' is 'https://d2nvs31859zcd8.cloudfront.net/54b18845c641d1343e6f_evanandkatelyn_39467301940_1731267082/160p30/index-dvr.m3u8'

Playlist url for selected quality '1080p60 (1920x1080)' is 'https://d2nvs31859zcd8.cloudfront.net/54b18845c641d1343e6f_evanandkatelyn_39467301940_1731267082/chunked/index-dvr.m3u8'

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1623

Starting parallel video chunk download
Number of video chunks to download: 1623
Maximum connection count: 10

Parallel video chunk download is running...

Starting temporary download folder cleanup!
Deleting directory 'D:\Other Stuff\E&K streams\Temp\7692587d6d15480f8909fbe29291c338'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. (One or more errors occurred. (The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.))
 ---> System.AggregateException: One or more errors occurred. (The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.)
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.<ThrowIfDisposed>g__ThrowObjectDisposedException|63_0()
   at System.Net.Sockets.NetworkStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState) in E:\Coding\twitchleecher-dx\TwitchLeecher\TwitchLeecher.Services\Services\DownloadService.cs:line 528
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.DownloadService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, TwitchPlaylist vodPlaylist, CancellationToken cancellationToken) in E:\Coding\twitchleecher-dx\TwitchLeecher\TwitchLeecher.Services\Services\DownloadService.cs:line 514
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2() in E:\Coding\twitchleecher-dx\TwitchLeecher\TwitchLeecher.Services\Services\DownloadService.cs:line 227
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
```

The download does happen successfully when I do not use my computer and no other device is using the internet heavily.

**Comment by schneidermanuel** [comment]
I am aware of this, you can chance the number of parallel chunks downloaded in the settings at the bottom. A smaller number will help! 
I think I should default this to a lower value.

**Comment by positron7120** [comment]
Thank you for the suggestion I reduced the maximum number of connections to 4 and the video downloaded without any error. I hope this suggestion will be helpful to the OP also.

**Comment by schneidermanuel** [comment]
I will close this as completed but lower the default value in a future version down to 5.
